#define CONE                0
#define SINGLE_WOOD         1
#define DOUBLE_WOOD         2
#define BOMB                3
#define BRICK               4
#define BRICK_BLOCK_1       5
#define BRICK_BLOCK_2       6
#define SCREWDRIVER         7
#define TOOL                8
#define ROCK_1              9
#define ROCK_2              10
#define LASER_VERTICAL      11
#define ROCK_BLOCK          12
#define TRASH_BAG           13
#define TRASH               14
#define HYDRANT             15
#define SPIKE               16
#define FIRE                17
#define RED_CAR             18
#define BLUE_CAR            19
#define N1                  20
#define N2                  21
#define N3                  22
#define X                   23
#define JOYSTICK            24
#define A                   25
#define C                   26
#define D                   27
#define E                   28
#define N                   29
#define P                   30
#define R                   31
#define S                   32
#define U                   33
#define V                   34
